export const data = [
  {
    title: "کارآموز طراحی سایت (وردپرس-دورکاری)",
    company: "هلدینگ دانلرن | donelearn",
    location: "همدان، ملایر",
    employment_type: "دورکاری",
    salary: "حقوق از ۱۱,۰۰۰,۰۰۰ تومان",
    posted_days_ago: "۱۱ روز پیش",
    state: true,
    link: "https://thumb2.jobinjacdn.com/WEjFVKtp8O5gFPXLR9oyREnoXuM=/fit-in/128x128/filters:strip_exif():fill(transparent):quality(100)/https://mstorage2.jobinjacdn.com/other/files/uploads/images/32b57085-201d-4ec7-b8d8-1178dc0155bc/main.png",
  },
  {
    title: "کارشناس پشتیبانی نرم‌افزار (همدان)",
    company: "سایان رایان اکباتان | Sayan",
    location: "همدان، همدان",
    employment_type: "تمام‌وقت",
    salary: "حقوق توافقی",
    posted_days_ago: "۲۴ روز پیش",
    state: false,
    link: "https://thumb2.jobinjacdn.com/_RIBXTMbJ0t4Bq7q2OceK6TC95Q=/fit-in/128x128/filters:strip_exif():fill(transparent):quality(100)/https://mstorage2.jobinjacdn.com/other/files/uploads/images/993642e5-46e1-41c7-b955-e0bdc0739d49/main.png",
  },
  {
    title: "برنامه‌نویس فرانت اند ( Front-End-همدان)",
    company: "سایان رایان اکباتان | Sayan",
    location: "همدان، همدان",
    employment_type: "تمام‌وقت",
    salary: "حقوق توافقی",
    posted_days_ago: "۲۸ روز پیش",
    state: false,
    link: "https://thumb2.jobinjacdn.com/_RIBXTMbJ0t4Bq7q2OceK6TC95Q=/fit-in/128x128/filters:strip_exif():fill(transparent):quality(100)/https://mstorage2.jobinjacdn.com/other/files/uploads/images/993642e5-46e1-41c7-b955-e0bdc0739d49/main.png",
  },
  {
    title: "طراح سایت (وردپرس-همدان)",
    company: "آیکو وب | Ico web",
    location: "همدان، همدان",
    employment_type: "تمام‌وقت",
    salary: "حقوق توافقی",
    posted_days_ago: "۳۶ روز پیش",
    state: false,
    link: "https://thumb2.jobinjacdn.com/5HpSxKAakKCTFq0jwOe0WcU8Kws=/fit-in/128x128/filters:strip_exif():fill(transparent):quality(100)/https://mstorage2.jobinjacdn.com/other/files/uploads/images/b574487a-4553-4ed6-8740-b418e67e6ef5/main.png",
  },
];
